services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: false
    depends_on:
      - postgres

  # TODO: frontend service
  # frontend:
  #   build: ./frontend

volumes:
  pgdata:
